ch(setup-react-project): Setup an empty react project
atlp-rwanda/elite-bn-fe pull request #1
Opened 2022-07-22 19:09 UTC by Francoise02

#### What does this PR do?

Set up an empty react project using Webpack 4, Babel, and the Airbnb linting option.

#### How should this be manually tested?

1. Clone branch, install packages but `npm i` or `yarn install` and  run `npm start` or `yarn start`
2. To test linting, run `lint` and fix the lining errors run `lintFix`

#### What are the relevant pivotal tracker stories?
[#182201515](https://www.pivotaltracker.com/story/show/182201515)

2022-07-25 06:21 UTC, Julienish14 approved these changes

2022-07-25 06:45 UTC, ishimweeli approved these changes

2022-07-25 07:04 UTC, kalisaNkevin approved these changes

2022-07-25 20:06 UTC, ericus123 requested changes

2022-07-25 20:06 UTC, ericus123 commented on src/components/App.js
> +export default App;
Use function based components other than class based.
They work better and are more updated.

2022-07-25 20:06 UTC, ericus123 commented on webpack.config.js
> +  },
try adding some other common loaders configurations here as well.
Like style loaders(css,scss) and images loaders (png , svg, jpg , ...).
with the current loaders configuration styles and images can't be loaded by webpack.

2022-07-25 20:06 UTC, ericus123 commented on webpack.config.js
> +}
what's the use of this?
remove it if not used

2022-07-25 20:06 UTC, ericus123 commented on package.json
> +    "lintFix": "eslint --fix --ext src/**/*.js",
don't use camelCase for scripts.
you can do this instead. `lint:fix`

2022-07-26 16:47 UTC, ericus123 approved these changes

2022-07-26 16:53 UTC, merged