fix(pre-commit): Prettier and Eslint configuration
atlp-rwanda/elite-bn-fe pull request #17
Opened 2022-08-02 14:52 UTC by Francoise02

#### What does this PR do?
Setup Prettier and Eslint pre-commits.
 
#### How should this be manually tested?

-   `yarn format` 
-   `yarn lint`
-   `git commit`

2022-08-02 15:58 UTC, kalisaNkevin approved these changes

2022-08-03 10:30 UTC, ericus123 requested changes

2022-08-03 10:30 UTC, ericus123 commented on .husky/pre-commit
> +git add -A
this doesn't have to be in the hook.

2022-08-03 10:32 UTC, ericus123 requested changes

2022-08-03 10:32 UTC, ericus123 commented on .husky/pre-commit
> +git add -A
this doesn't have to be in the hook
`git add -A`.
It's optional and is handled by git

2022-08-03 16:21 UTC, ericus123 approved these changes

2022-08-03 16:21 UTC, merged