ft(registration-client-182201524):Users should be able Signup/Registe…
atlp-rwanda/elite-bn-fe pull request #27
Opened 2022-08-10 11:19 UTC by kalisaNkevin

#### What does this PR do?

Users should be able Signup/Register to Barefoot Nomad

#### Description of Task to be completed?

`.`The sign up form should present to the user descriptive validation errors incase of any.
`.`The user should receive verification link on email upon successful registration

#### How should this be manually tested?

After cloning this repository, Switch to this branch:  `ft-registration-client-182201524`
The run: `yarn install `
To run the app:  `yarn start`
To run the test:  `yarn test`

#### Any background context you want to provide?

Fetching API from the backend and material UI framework for css 

#### What are the relevant pivotal tracker stories?

https://www.pivotaltracker.com/story/show/182201524

2022-08-12 10:52 UTC, uwishema11 approved these changes

2022-08-12 10:53 UTC, Julienish14 approved these changes

2022-08-12 11:03 UTC, munyanezaarmel reviewed
You don't have to import axios again it is already set you have to import API which found in utils and also backend UR should be in environment variables

2022-08-12 12:54 UTC, ishimweeli approved these changes

2022-08-13 09:47 UTC, kalisaNkevin commented
> You don't have to import axios again it is already set you have to import API which found in utils and also backend UR should be in environment variables

2022-08-13 10:54 UTC, munyanezaarmel reviewed
Works fine but I can suggest when registration is successful a page should navigate to login screen instead of home screen also check coveralls

2022-08-14 16:05 UTC, ericus123 commented
<img width="660" alt="Screenshot 2022-08-14 at 18 01 31" src="https://user-images.githubusercontent.com/58434968/184545233-db351775-394a-442f-bc26-769a1109dae9.png">

Fix the validations.
- I'm seeing errors for no reason.
- These errors are confusing.
`enter your username is equired`
either say `enter your username` or `username is equired`.
do same for other inputs as well

2022-08-14 16:11 UTC, ericus123 requested changes

2022-08-14 16:11 UTC, ericus123 commented on test/app.test.js
> +
add a signup test file separately and add signup tests.
test the inputs individually as well.

2022-08-14 16:11 UTC, ericus123 commented on src/Views/RegisterView.js
> +    <div>
remove these div tags and have signup component only here

2022-08-15 06:01 UTC, ericus123 commented
Signup doesn't work???
![Uploading Screenshot 2022-08-15 at 07.59.36.png…]()

2022-08-15 06:02 UTC, ericus123 commented
Make sure to use only material UI alerts

2022-08-15 06:02 UTC, ericus123 requested changes

2022-08-15 06:02 UTC, ericus123 commented on test/registartion.test.js
> +})
is this the only test for registration ???

2022-08-15 06:04 UTC, ericus123 commented
@kalisaNkevin  How is `dist` folder visible among changes?
Isn't it ignored??
Make sure it doesn't appear among git changes.

2022-08-21 18:34 UTC, munyanezaarmel approved these changes
add .dist in gitignore

2022-08-21 19:52 UTC, closed without merging