ft-(user-login): Users should be able to Login to Barefoot Nomad
atlp-rwanda/elite-bn-fe pull request #28
Opened 2022-08-12 14:05 UTC by Julienish14

What does this PR do?
Users should be able to Login to Barefoot Nomad application

How should this be manually tested?

run yarn start
lick on the login link on the landing page
Any background context you want to provide?
What are the relevant pivotal tracker stories?
[#182201526](https://www.pivotaltracker.com/story/show/182201526)

2022-08-15 08:56 UTC, didasmbalanya commented
@Julienish14 When I open the app, it should always redirect to login if the user is not logged in, and to dashboard if the user is logged in

2022-08-18 10:36 UTC, ishimweeli approved these changes

2022-08-18 12:16 UTC, ericus123 requested changes

2022-08-18 12:16 UTC, ericus123 commented on test/mock/handlers/auth.handler.js
> +  rest.post(`https://bravo-bfn-be.herokuapp.com/api/v1/user/login`, (req, res, ctx) => {
use url from envs please

2022-08-18 14:43 UTC, Julienish14 commented on test/mock/handlers/auth.handler.js
> +  rest.post(`https://bravo-bfn-be.herokuapp.com/api/v1/user/login`, (req, res, ctx) => {
Done.

2022-08-22 09:09 UTC, ericus123 commented
@Julienish14 rebase

2022-08-23 05:22 UTC, ericus123 commented
@Julienish14 the coverage is dropped

2022-08-23 11:12 UTC, kalisaNkevin approved these changes

2022-08-27 07:29 UTC, ericus123 commented on src/components/Authentications/login.js
> +        console.log(res)
remove this log

2022-08-27 07:29 UTC, ericus123 commented on src/components/Authentications/login.js
> +          navigate('/')
store token in redux state and persist it instead of using local storage.
A user can directly change it in local storage and the token will be useless

2022-08-27 07:29 UTC, ericus123 commented on utils/privateRoute.js
> +            // console.log('is loggedin', isLoggedIn)
remove unused codes

2022-08-27 09:24 UTC, Julienish14 commented on src/components/Authentications/login.js
> +        console.log(res)
this log is not written in current codes

2022-08-27 09:24 UTC, Julienish14 commented on src/components/Authentications/login.js
> +          navigate('/')
in current codes token is stored in redux too

2022-08-27 12:14 UTC, ericus123 approved these changes

2022-08-27 12:14 UTC, merged