(ft-client-logout-182201571):Logout Functionality
atlp-rwanda/elite-bn-fe pull request #30
Opened 2022-08-13 20:50 UTC by ishimweeli

to test this pr please  press logout button

2022-08-13 21:22 UTC, kalisaNkevin submitted a review, later dismissed
Import api from the utils , and also there are no tests and lastly i would recommend you to use redux/toolkit.

2022-08-15 06:11 UTC, ericus123 requested changes

2022-08-15 06:11 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +   sweerAlt.fire('Oops...', `${err.response.data.message}`, 'error');
You should not use sweet alert. 
Use material UI alerts

2022-08-15 06:11 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +  if (res.status === 200) {
status check here is unnecessary.

2022-08-15 06:11 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +const url = "https://elite-bn-be.herokuapp.com/api/v1/user/logout"
Why do you have this hardcoded ?????

2022-08-15 21:23 UTC, ericus123 commented
This is what I'm getting.
![Uploading Screenshot 2022-08-15 at 23.22.29.png…]()

2022-08-15 21:23 UTC, ericus123 submitted a review, later dismissed

2022-08-15 21:23 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +    )
No need for alert on logout

2022-08-22 09:09 UTC, ericus123 commented
@ishimweeli rebase

2022-08-29 09:52 UTC, didasmbalanya commented
Please fix failing tests so that it can be tested

2022-08-30 10:33 UTC, didasmbalanya commented
Logout button does not seem to work on the review app. No action on click

2022-08-30 20:19 UTC, ishimweeli commented
> Logout button does not seem to work on the review app. No action on click

I have fixed all things mentioned above

2022-08-31 04:50 UTC, ericus123 requested changes

2022-08-31 04:50 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +    //     };
remove this

2022-08-31 04:50 UTC, ericus123 commented on src/components/auth/auth.logout.js
> +      console.log(res)
remove this

2022-08-31 04:54 UTC, ericus123 commented
Logout should be done only by clicking one button.
Why are you linking it with two buttons.
The button in the nav dropdown is enough.

@ishimweeli fix that ASAP

2022-08-31 06:26 UTC, ericus123 approved these changes

2022-08-31 06:27 UTC, merged