fix(user-register-token)
atlp-rwanda/elite-bn-fe pull request #40
Opened 2022-08-25 09:56 UTC by kalisaNkevin

#### What does this PR do?
fix the token 
#### Description of Task to be completed?
`yarn start`
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)

2022-08-25 14:55 UTC, ericus123 commented
@kalisaNkevin rebase

2022-08-30 10:50 UTC, didasmbalanya requested changes
After logging in, and a token being stored I was able to access to '/register' view. Please fix this ASAP

2022-08-30 14:47 UTC, didasmbalanya approved these changes

2022-08-30 14:51 UTC, ericus123 approved these changes

2022-08-30 14:52 UTC, merged